---
title: "Simulation"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```


## Grand mean functions
```{r}
grand_mean_lm = function(fit, mountain, beta) {
  ind = (mountain+1):(2*mountain)
  covariance = vcov(fit)[ind,ind]
  effect = summary(fit)$coefficients[ind, 1]
  weights = ((1/apply(covariance, 1,sum))/ (sum(1/apply(covariance,1,sum))))
  effect_sizes = effect
  eff = weighted.mean(effect_sizes, weights)
  var1 = 0
  for(i in 1:mountain){
    for(j in 1:mountain){
      var1 = var1 + covariance[i,j]*weights[i]*weights[j]  
    }
  }
  var2 = sum((weights/(mountain-1))*(effect_sizes-eff)^2)  
  se = sqrt(var1 + var2)
  p_value = 2*pt(abs(eff/se),df=mountain-1, lower.tail = FALSE)
  bound = qt(0.975, df = mountain-1)
  confs = cbind( eff - bound*se, eff + bound*se) 
  return(c(eff, p_value, se, as.integer(beta > confs[1,1] & beta < confs[1,2])))
}
grand_mean = function(mean, V, beta) {
  covariance = V
  mountain = ncol(V)
  effect = mean
  effect_sizes = effect
  # eff = weighted.mean(effect_sizes, weights)
  # var1 = 0
  # for(i in 1:mountain){
  #   for(j in 1:mountain){
  #     var1 = var1 + covariance[i,j]*weights[i]*weights[j]  
  #   }
  # }
  C_1 = solve(V)
  weights = rowSums(C_1) * (1/sum(C_1))
  
  eff = sum(C_1 %*% diag(effect))*(1/sum(C_1))
  var1 = ((1/sum(C_1)))
  var1=0
  
  var2 = sum((weights/(mountain-1))*(effect-eff)^2)  
  
  se = sqrt(var1 + var2)
  p_value = 2*pt(abs(eff/se),df=mountain-1, lower.tail = FALSE)
  bound = qt(0.975, df = mountain-1)
  confs = cbind( eff - bound*se, eff + bound*se) 
  return(c(eff, p_value, se, as.integer(beta > confs[1,1] & beta < confs[1,2])))
}
grand_mean2 = function(mean, V, beta) {
  covariance = V
  mountain = ncol(V)
  effect = mean
  
  C_1 = solve(V)
  eff = sum(C_1 %*% diag(effect))*(1/sum(C_1))
  se = sqrt((1/sum(C_1)))
  p_value = 2*pt(abs(eff/se),df=mountain-1, lower.tail = FALSE)
  bound = qt(0.975, df = mountain-1)
  confs = cbind( eff - bound*se, eff + bound*se) 
  return(c(eff, p_value, se, as.integer(beta > confs[1,1] & beta < confs[1,2])))
}

grand_mean3 = function(mean, V, beta) {
  covariance = V
  mountain = ncol(V)
  effect = mean
  
  C_1 = pracma::inv(V)#solve(V)
  eff = sum(C_1 %*% diag(effect))*(1/sum(C_1))
  se = sqrt((1/sum(C_1))) #* sqrt(mountain-1)
  mountain = 2
  p_value = 2*pt(abs(eff/se),df=mountain-1, lower.tail = FALSE)
  bound = qt(0.975, df = mountain-1)
  confs = cbind( eff - bound*se, eff + bound*se) 
  return(c(eff, p_value, se, as.integer(beta > confs[1,1] & beta < confs[1,2])))
}

grand_mean4 = function(mean, V, beta) {
  covariance = V
  mountain = ncol(V)
  effect = mean
  
  # C_1 = pracma::inv(V)#solve(V)
  # eff = sum(C_1 %*% diag(effect))*(1/sum(C_1))
  # se = sqrt((1/sum(C_1)))
  sigmas = diag(V)
  C = sum(1/sigmas)
  eff = sum(effect/sigmas) / C
  se = sqrt( 1/ C)
  
  p_value = 2*pt(abs(eff/se),df=mountain-1, lower.tail = FALSE)
  bound = qt(0.975, df = mountain-1)
  confs = cbind( eff - bound*se, eff + bound*se) 
  return(c(eff, p_value, se, as.integer(beta > confs[1,1] & beta < confs[1,2])))
}


grand_mean_metafor = function(means, V, beta, fixed = FALSE, tresh = FALSE, method = "REML") {
  mountain = ncol(V)
  if(tresh) V[V < 0.0001] = 0
  id = as.factor(1:mountain)
  if(!fixed) meta = metafor::rma.mv(means, V = V, test = "t", method = method, random = ~ 1 | id)
  else meta = metafor::rma.mv(means, V = V, test = "t", method = method)
  return(c(meta$beta, meta$pval, meta$se, as.integer(beta > meta$ci.lb & beta < meta$ci.ub)))
}
grand_mean_uni = function(means, V, beta, fixed = FALSE, tresh = FALSE, method = "REML") {
  mountain = ncol(V)
  if(tresh) V[V < 0.0001] = 0
  id = as.factor(1:mountain)
  meta = metafor::rma.uni(means, vi = diag(V), test = "t", method = method)
  return(c(meta$beta, meta$pval, meta$se, as.integer(beta > meta$ci.lb & beta < meta$ci.ub)))
}
```

## Simulate with multivariate normal distribution
```{r}
simulate_mvn = function(n, diagonals) {
  # samples = mvtnorm::rmvnorm(1, sigma = diag(diagonals))
  # means = samples[1,]
  # V = diag(diagonals)
  samples = sapply(1:n, function(i) rnorm(10,0, sd = diagonals[i]))
  means = apply(samples, 2, mean)
  means = samples[1,]
  V = diag(apply(samples, 2, var))
  return(list(means = means, V = diag(diagonals)))
}

simulate_lm = function(groups = c(20, 20, 20)) {
  g = as.factor(unlist(sapply(1:length(groups), function(i) rep(i, groups[i]))))
  x = runif(sum(groups), -1, 1)
  y = rnorm(sum(groups), sd =0.5)
  fit_lm = lm(y ~ 0+x*g-x)
  summary(fit_lm)
  ind = (length(groups)+1):(2*length(groups))
  return(list(means = coef(fit_lm)[ind], V = vcov(fit_lm)[ind, ind]))
}

results_gm1 = 
  sapply(1:5000, function(i) {
    sim = simulate_lm(c(5, 50, 50, 50, 50, 50, 100, 100, 100, 100))
    return(grand_mean(sim$means, sim$V, 0))
  })


hist(t(results_gm1)[,2])
results_gm2 = 
  sapply(1:5000, function(i) {
    sim = simulate_lm(c(5, 50, 50, 50, 50, 50, 100, 100, 100, 100))
    return(grand_mean2(sim$means, sim$V, 0))
  })
hist(t(results_gm2)[,2])
results_meta = 
  sapply(1:5000, function(i) {
    sim = simulate_lm(c(5, 50, 50, 50, 50, 50, 100, 100, 100, 100))
    return(grand_mean_metafor(sim$means, sim$V, 0, fixed = TRUE,method = "FE"))
  })
hist(t(results_meta)[,2])
```


```{r}
library(tidyverse)
simulate_lm_re = function(groups = c(20, 20, 20)) {
  g = as.factor(unlist(sapply(1:length(groups), function(i) rep(i, groups[i]))))
  x = runif(sum(groups), -1, 1)
  X <- matrix(c(rep(1, sum(groups)), x), nrow = sum(groups))
  beta = 0.0   # Temperature effect meaning when the temperature increases 1 degree the respective variable also does 
  beta0 = 0.0   # Intercept: the mean height of a reporductive plant  
  
  randintercep <- rnorm(length(groups), mean = beta0, sd = 0.7)  # random intercept
  randslope <- rnorm(length(groups), mean = beta, sd = 0.7)      # random slope
  
  mu <- sapply(1:sum(groups), FUN = function(j) X[j,] %*% c(randintercep[g[j]],randslope[g[j]]))
  
  sigma <- 0.3
  y <- rnorm(sum(groups), mu, sd = sigma)
  
  data = data.frame(iv = X[,2], id = g)
  
  d <- data %>% 
    # Grand mean centering (CMC)
    mutate(iv.gmc = iv-mean(iv)) %>%
    # Person mean centering (more generally, centering within cluster)
    group_by(id) %>% 
    mutate(iv.cm = mean(iv),
           iv.cwc = iv-iv.cm) %>%
    ungroup %>%
    # Grand mean centering of the aggregated variable
    mutate(iv.cmc = iv.cm-mean(iv.cm))
  
  d$y = y
  
  fit_lm = lm(y ~ 0+id+iv.cwc:id, data = d)
  #fit_lm = lm(y ~ 0+x:g + g)
  summary(fit_lm)
  ind = (length(groups)+1):(2*length(groups))
  sim = list(means = coef(fit_lm)[ind], V = vcov(fit_lm)[ind, ind])
  return(sim)
}


getParsBT2 = function(samples) {
  ll = function(par) {
    mean = par[1]
    sd = par[2]
    if(sd < 0.0) return(Inf)
    ll = sum(sapply(1:nrow(samples), function(i) sum(dnorm(rnorm(1000, samples[i,1], samples[i,2]), mean, sd, log =TRUE))))
    return(-ll)
  }
  pp = optim(c(0.1, 0.1), ll)$par
  return(c(pp[1], pp[2]/sqrt(nrow(samples)-1)))
}
grand_mean = function(mean, V, beta) {
  covariance = V
  mountain = ncol(V)
  effect = mean
  effect_sizes = effect

  multi = TRUE
  if(multi) {
    C_1 = solve(V)
    weights = rowSums(C_1) * (1/sum(C_1))
    eff = sum(C_1 %*% (effect))*(1/sum(C_1))
    var1 = ((1/sum(C_1)))
  } else {
    sigmas = diag(V)
    C = sum(1/sigmas)
    eff = sum(effect/sigmas) / C
    var1 = ( 1/ C)
    weights = sigmas/sum(sigmas)
  }
  #var1=0
  var2 = 1/(mountain)*sum((weights)*(effect-eff)^2)
  se = sqrt(var1 + var2)
  
  #samples = cbind(mean, diag(V))
  #RR = getParsBT2(samples)
  #eff = RR[1]
  #se = RR[2]
  
  boot = TRUE
  if(boot) {
    SS = as.vector(mvtnorm::rmvnorm(1000, mean = mean, sigma = V))
    eff = mean(SS)
    se = var(SS)
  }
  
  p_value = 2*pt(abs(eff/se),df=mountain*10000-1, lower.tail = FALSE)
  bound = qt(0.975, df = mountain*10000-1)
  confs = cbind( eff - bound*se, eff + bound*se) 
  return(c(eff, p_value, se, as.integer(beta > confs[1,1] & beta < confs[1,2])))
}

results_gm1 = 
  sapply(1:1000, function(i) {
    sim = simulate_lm_re(c(rep(30, 200), 30))
    return(grand_mean(sim$means, sim$V, 0))
  })
hist(t(results_gm1)[,2], breaks = 20L)
mean(t(results_gm1)[,2] < 0.05)







results_gm2 = 
  sapply(1:1000, function(i) {
    sim = simulate_lm_re(c(20, 20, 20, 3, 50, 50, 50, 100))
    return(grand_mean2(sim$means, sim$V, 0))
  })
hist(t(results_gm2)[,2])

results_gm3 = 
  sapply(1:1000, function(i) {
    sim = simulate_lm_re(c(20, 20, 20, 3, 50, 50, 50, 100))
    return(grand_mean3(sim$means, sim$V, 0))
  })
hist(t(results_gm3)[,2])

results_gm4 = 
  sapply(1:1000, function(i) {
    sim = simulate_lm_re(c(20, 20, 20, 3, 50, 50, 50, 100))
    return(grand_mean4(sim$means, sim$V, 0))
  })
hist(t(results_gm4)[,2], breaks = 40L)

results_gm5 = 
  sapply(1:1000, function(i) {
    sim = simulate_lm_re2(c(20, 20, 20, 3, 50, 50, 50, 100))
    return(sim)
  })
hist(results_gm5, breaks = 40L)

results_meta = 
  sapply(1:5000, function(i) {
    sim = simulate_lm_re(c(20, 20, 20))
    return(grand_mean_metafor(sim$means, sim$V, 0, fixed = TRUE,method = "FE"))
  })
hist(t(results_meta)[,2])



sim = simulate_lm_re(c(20, 20, 20, 3, 50, 50, 50, 100))

grand = grand_mean4(sim$means, sim$V, 0)
sum((sim$means- grand[1])^2 / grand[3]^2)
```

